name:  CKTESTWRKFLW

on:
  push:
    branches: [ main ]

jobs:
  cccck:

    runs-on: ubuntu-20.04
    env:
      STORE_PASS: test@cake_wallet
      KEY_PASS: test@cake_wallet

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'

      - name: Flutter action
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.x'
          channel: stable

      - name: Install package dependencies
          sudo apt-get install -y curl unzip automake build-essential file pkg-config git python libtool libtinfo5 cmake clang

      - name: INIT BUILD
        run: |
          sudo mkdir -p /opt/android
          sudo chown $USER /opt/android
          cd /opt/android
          git clone https://github.com/qweewqi/qq2.git --branch main
          cd cake_wallet/scripts/android/
          ./install_ndk.sh
          source ./app_env.sh cakewallet
          ./app_config.sh

          cd /opt/android/cake_wallet/scripts/android/
          source ./app_env.sh cakewallet
          ./build_all.sh
          ./copy_monero_deps.sh

          cd /opt/android/cake_wallet
          flutter pub get

          cd /opt/android/cake_wallet/android/app
          keytool -genkey -v -keystore key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias testKey -noprompt -dname "CN=CakeWallet, OU=CakeWallet, O=CakeWallet, L=Florida, S=America, C=USA" -storepass $STORE_PASS -keypass $KEY_PASS

          cd /opt/android/cake_wallet
          flutter packages pub run tool/generate_android_key_properties.dart keyAlias=testKey storeFile=key.jks storePassword=$STORE_PASS keyPassword=$KEY_PASS
          cd /opt/android/cake_wallet
          echo "################################################################ LOCALIZATION TTTEEESSSTTT #######################################################"
          flutter packages pub run tool/generate_localization.dart
          echo "################################################################ LOCALIZATION TTTEEESSSTTT END #######################################################"
          cd /opt/android/cake_wallet
          cd cw_core && flutter pub get && flutter packages pub run build_runner build --delete-conflicting-outputs && cd ..
          cd cw_monero && flutter pub get && flutter packages pub run build_runner build --delete-conflicting-outputs && cd ..
          cd cw_bitcoin && flutter pub get && flutter packages pub run build_runner build --delete-conflicting-outputs && cd ..
          cd cw_haven && flutter pub get && flutter packages pub run build_runner build --delete-conflicting-outputs && cd ..
          flutter packages pub run build_runner build --delete-conflicting-outputs
          cd /opt/android/cake_wallet
          touch lib/.secrets.g.dart
          echo "const salt = '0000000000000000000000000000';" > lib/.secrets.g.dart
          echo "const keychainSalt = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const key = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const walletSalt = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const shortKey = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const backupSalt = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const backupKeychainSalt = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const changeNowApiKey = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const wyreSecretKey = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const wyreApiKey = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const wyreAccountId = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const moonPayApiKey = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const moonPaySecretKey = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const sideShiftAffiliateId = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const sideShiftApiKey = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const simpleSwapApiKey = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const onramperApiKey = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const anypayToken = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const ioniaClientId = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const twitterBearerToken = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const trocadorApiKey = '0000000000000000000000000000';" >> lib/.secrets.g.dart
          echo "const trocadorExchangeMarkup = '0000000000000000000000000000';" >> lib/.secrets.g.dart
      
      - name: Rename app
        run: echo -e "id=com.cakewallet.test\nname=$GITHUB_HEAD_REF" > /opt/android/cake_wallet/android/app.properties

      - name: Build
        run: |
          cd /opt/android/cake_wallet
          flutter build apk --release
          
      - name: Rename apk file
        run: |
          cd /opt/android/cake_wallet/build/app/outputs/apk/release
          mkdir test-apk
          cp app-release.apk test-apk/$GITHUB_HEAD_REF.apk
          
      - name: Upload Artifact
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: /opt/android/cake_wallet/build/app/outputs/apk/release/test-apk/          
          
